# Generated by Django 2.2.12 on 2020-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=32, unique=True)),
                ('code', models.TextField()),
                ('result', models.TextField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
