FROM ubuntu:18.04


ARG APPDIR=/root/goonk
ARG APPNAME=goonk

RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip
# RUN pip3 install setuptools

RUN mkdir ${APPDIR}
WORKDIR ${APPDIR} 
ADD . ${APPDIR}

RUN pip3 install --no-cache-dir -r ${APPDIR}/requirements.txt

# remove build pkgs
# RUN apt-get remove --purge -y build-essential libpcre3-dev libpq-dev python3-pip gcc python3-dev


# uwsgi configuration
# Note: port as env var doesnt work, use build time args instead
ARG UWSGI_HTTP
ENV UWSGI_WSGI_FILE=${APPNAME}/wsgi.py
ENV UWSGI_HTTP=:${UWSGI_HTTP} UWSGI_MASTER=1 UWSGI_HTTP_AUTO_CHUNKED=1 UWSGI_HTTP_KEEPALIVE=1 UWSGI_LAZY_APPS=1 UWSGI_WSGI_ENV_BEHAVIOR=holy

# django env vars
ENV DJANGO_ENVIRONMENT=live

EXPOSE ${UWSGI_HTTP}
CMD ["uwsgi", "--show-config"]
